### ISSUE TITLE
Part 2: Elliptic curve arithmetic

### ISSUE THREAD

**Issue by dapinkone** [dapinkone/TCSS487Project#6]
## Implementing Ed448-Goldilocks with BigInteger.

Building a library & app for asymmetric encryption and digital signatures at the 256-bit security level.
- [x] DHIES encryption
- [x] Schnorr signatures, with elliptic curves

Note, all arithmetic is modulo  p. p is a specific prime defined in the Ed448-Goldilocks spec.
> p := 2^448  - 2^224 - 1

- [x] Need a data structure to represent the goldilocks pair (x, y)
  - [x] constructor for neutral element
  - [x] constructor for curve point given it's x and y's least sig bit.
  - [x] .equals method test for equality
  - [x] .opposite method to obtain opposite of a point
  - [x] current.add(other) method to sum two points
    - [x] tests written/passing 
  - [x] .mul() to support scalar multiplication
    - [x] tests written/passing 

### services:

- [x] Generate an elliptic key pair from a given passphrase
- [x] write the public key to a file
- [x] BONUS: Encrypt the private key from that pair under the given password and write it to a different file as well.
- [x] Encrypt a data file under a given elliptic public key file and write the ciphertext to a file.
- [x] BONUS: Encrypt text input by the user directly to the app instead of having to read it from a file (but write the ciphertext to a file).
- [x]  Decrypt a given elliptic-encrypted file from a given password and write the decrypted data to a file.
- [x] Sign a given file from a given password and write the signature to a file.
- [x] BONUS: Sign text input by the user directly to the app instead of having to read it from a file (but write the signature to a file).
- [x] Verify a given data file and its signature file under a given public key file.
- [x] BONUS: Verify text input by the user directly to the app instead of having to read it from a file (but read the signature from a file).
- [x] The actual instructions to use the app and obtain the above services must be part of your project report (in PDF).

**Comment by Hyunggilwoo** [comment]
Question on implementing the y_0 of the GoldilockPair's public generator:
How do we compute y_0?
Given that:
1. public generator (G) = (x_0, y_0)
2. x = plus_or_minus sqrt( (1 - y^2) / (1 + 39081y^2) mod p)
3. x_0 = -3 (mod p)

Do we have compute y from the equation to compute x?

**Comment by Hyunggilwoo** [comment]
KMACXOF256. Does Part 1 need to incorporate BigInteger instead of int?

**Comment by Hyunggilwoo** [comment]
I am debating on if we need to create a separate class to generate a Schnorr signature, or can whether Elliptic Curve class should have the Schnorr signature method, or maybe the KMACXOF256 should have access to it. Right now, I am leaning towards creating a separate class to generate a key pair of Schnorr Signature

**Comment by dapinkone** [comment]
> KMACXOF256. Does Part 1 need to incorporate BigInteger instead of int?

Posting here for reference, verdict was "mostly no"; extending a few select functions for utility moving forward, but the project requirements do not require this functionality in part 1's section.



> I am debating on if we need to create a separate class to generate a Schnorr signature, or can whether Elliptic Curve class should have the Schnorr signature method, or maybe the KMACXOF256 should have access to it. Right now, I am leaning towards creating a separate class to generate a key pair of Schnorr Signature

Java / OOP style is pretty heavy on classes. It's probably fine to make a class for this. It's a thing, with associated properties and functionality. sounds like a class to me. We'll see how much it has in common with other classes as the project matures.

> Question on implementing the y_0 of the GoldilockPair's public generator: How do we compute y_0? Given that:
> 
>     1. public generator (G) = (x_0, y_0)
> 
>     2. x = plus_or_minus sqrt( (1 - y^2) / (1 + 39081y^2) mod p)
> 
>     3. x_0 = -3 (mod p)
> 
> 
> Do we have compute y from the equation to compute x?

See implementation of [ElipticCurve.f](https://github.com/dapinkone/TCSS487Project/blob/f24f4910a61b2f8ef3b56dbef16340d384ced87f/src/EllipticCurve.java#L185)
or the instantiation of G just above. These may answer the question

**Comment by dapinkone** [comment]
Project completed as far as needed, closing ticket.
